### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by nicovak** [lann/tcp-timeout-ruby#3]
Hello @lann, thank you for this awesome gem !
I can that that code from 2016 isn't bundled in a new release.

Can you please release a new version (0.1.2) that includes https://github.com/lann/tcp-timeout-ruby/commit/5bff959e54bfb0d1bb9bdcd73c7196629b5291f5 ?
It would be great.

**Comment by lann** [comment]
Are you sure you need this? IO has had nonblocking methods since Ruby 2.0.

**Comment by nicovak** [comment]
I think yes, because if the length is not specified It raises an Exception

Doesn't raise an error:

```ruby
socket.read(25)
```

Raise an error:

```ruby
socket.read
```

**Comment by lann** [comment]
If I'm understanding your point: I don't think it makes sense to read(nil) in a nonblocking context.

Also, check out the documentation for IO::read_nonblock; you should expect to get certain exceptions when the read buffer is empty, even with bounded reads.

**Comment by lann** [comment]
To clarify: I think it is better now to use *_nonblock + IO::select with a timeout.

**Comment by nicovak** [comment]
Thank you for your responses, I finally used example from the doc : 

```ruby
s = TCPSocket.new crendential[:ip], crendential[:port]
```

```ruby
begin
  Timeout.timeout 5 do
    while line = s.gets
      response += line
    end
  end
  rescue Timeout::Error
  puts 'DONE!'
end
```
